export const UPDATE_AVATAR_REQUEST = '@user/UPDATE_AVATAR_REQUEST';
export const UPDATE_AVATAR_SUCCESS = '@user/UPDATE_AVATAR_SUCCESS';
export const UPDATE_AVATAR_FAILURE = '@user/UPDATE_AVATAR_FAILURE';
