export const CREATE_VIDEO_REQUEST = '@video/CREATE_VIDEO_REQUEST';
export const CREATE_VIDEO_SUCCESS = '@video/CREATE_VIDEO_SUCCESS';
export const CREATE_VIDEO_FAILURE = '@video/CREATE_VIDEO_FAILURE';

export const UPDATE_VIDEO_REQUEST = '@video/UPDATE_VIDEO_REQUEST';
export const UPDATE_VIDEO_SUCCESS = '@video/UPDATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_FAILURE = '@video/UPDATE_VIDEO_FAILURE';

export const DELETE_VIDEO_REQUEST = '@video/DELETE_VIDEO_REQUEST';
export const DELETE_VIDEO_SUCCESS = '@video/DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_FAILURE = '@video/DELETE_VIDEO_FAILURE';
