export const CREATE_MEET_REQUEST = '@meet/CREATE_MEET_REQUEST';
export const CREATE_MEET_SUCCESS = '@meet/CREATE_MEET_SUCCESS';
export const CREATE_MEET_FAILURE = '@meet/CREATE_MEET_FAILURE';

export const DELETE_MEET_REQUEST = '@meet/DELETE_MEET_REQUEST';
export const DELETE_MEET_SUCCESS = '@meet/DELETE_MEET_SUCCESS';
export const DELETE_MEET_FAILURE = '@meet/DELETE_MEET_FAILURE';
