export const CREATE_REPORT_REQUEST = '@report/CREATE_REPORT_REQUEST';
export const CREATE_REPORT_SUCCESS = '@report/CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAILURE = '@report/CREATE_REPORT_FAILURE';
