export const CREATE_VIDEO_REQUEST = '@video/CREATE_VIDEO_REQUEST';
export const CREATE_VIDEO_SUCCESS = '@video/CREATE_VIDEO_SUCCESS';
export const CREATE_VIDEO_FAILURE = '@video/CREATE_VIDEO_FAILURE';

export const UPDATE_VIDEO_REQUEST = '@video/UPDATE_VIDEO_REQUEST';
export const UPDATE_VIDEO_SUCCESS = '@video/UPDATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_FAILURE = '@video/UPDATE_VIDEO_FAILURE';

export const DELETE_VIDEO_REQUEST = '@video/DELETE_VIDEO_REQUEST';
export const DELETE_VIDEO_SUCCESS = '@video/DELETE_VIDEO_SUCCESS';
export const DELETE_VIDEO_FAILURE = '@video/DELETE_VIDEO_FAILURE';

export const UPLOAD_THUMBNAIL_REQUEST = '@user/UPLOAD_THUMBNAIL_REQUEST';
export const UPLOAD_THUMBNAIL_SUCCESS = '@user/UPLOAD_THUMBNAIL_SUCCESS';
export const UPLOAD_THUMBNAIL_FAILURE = '@user/UPLOAD_THUMBNAIL_FAILURE';

export const CANCEL_THUMBNAIL = '@user/CANCEL_THUMBNAIL';

export const UPLOAD_THUMBNAIL_REQUEST_SEND =
  '@video/UPLOAD_THUMBNAIL_REQUEST_SEND';
